C:\VulkanSDK\1.3.275.0\Bin\glslc.exe img_sqrt.comp -o img_sqrt.spv
C:\VulkanSDK\1.3.275.0\Bin\glslc.exe img_max_reduce.comp -o img_max_reduce.spv
C:\VulkanSDK\1.3.275.0\Bin\glslc.exe img_normalize.comp -o img_normalize.spv
C:\VulkanSDK\1.3.275.0\Bin\glslc.exe img_smooth.comp -o img_smooth.spv
C:\VulkanSDK\1.3.275.0\Bin\glslc.exe img_downsample.comp -o img_downsample.spv
C:\VulkanSDK\1.3.275.0\Bin\glslc.exe img_upsample.comp -o img_upsample.spv
C:\VulkanSDK\1.3.275.0\Bin\glslc.exe img_smooth_upsampled.comp -o img_smooth_upsampled.spv
C:\VulkanSDK\1.3.275.0\Bin\glslc.exe img_difference.comp -o img_difference.spv
C:\VulkanSDK\1.3.275.0\Bin\glslc.exe img_addition.comp -o img_addition.spv
C:\VulkanSDK\1.3.275.0\Bin\glslc.exe img_sdev.comp -o img_sdev.spv
C:\VulkanSDK\1.3.275.0\Bin\glslc.exe img_histogram_render.comp -o img_histogram_render.spv
C:\VulkanSDK\1.3.275.0\Bin\glslc.exe img_histogram_max.comp -o img_histogram_max.spv
C:\VulkanSDK\1.3.275.0\Bin\glslc.exe contrast_curve_generate.comp -o contrast_curve_generate.spv
C:\VulkanSDK\1.3.275.0\Bin\glslc.exe contrast_curve_render.comp -o contrast_curve_render.spv
C:\VulkanSDK\1.3.275.0\Bin\glslc.exe contrast_curve_apply.comp -o contrast_curve_apply.spv
C:\VulkanSDK\1.3.275.0\Bin\glslc.exe img_to_rgb.comp -o img_to_rgb.spv
C:\VulkanSDK\1.3.275.0\Bin\glslc.exe img_linear.comp -o img_linear.spv
C:\VulkanSDK\1.3.275.0\Bin\glslc.exe img_cnr.comp -o img_cnr.spv
C:\VulkanSDK\1.3.275.0\Bin\glslc.exe gradation_curve_generate.comp -o gradation_curve_generate.spv
C:\VulkanSDK\1.3.275.0\Bin\glslc.exe gradation_curve_render.comp -o gradation_curve_render.spv
C:\VulkanSDK\1.3.275.0\Bin\glslc.exe gradation_histogram.comp -o gradation_histogram.spv
C:\VulkanSDK\1.3.275.0\Bin\glslc.exe img_apply_gradation_curve.comp -o img_apply_gradation_curve.spv
C:\VulkanSDK\1.3.275.0\Bin\glslc.exe img_relevant.comp -o img_relevant.spv
C:\VulkanSDK\1.3.275.0\Bin\glslc.exe clahe_histogram.comp -o clahe_histogram.spv
C:\VulkanSDK\1.3.275.0\Bin\glslc.exe clahe_grad_curve.comp -o clahe_grad_curve.spv
C:\VulkanSDK\1.3.275.0\Bin\glslc.exe clahe_grad_curve_apply.comp -o clahe_grad_curve_apply.spv
C:\VulkanSDK\1.3.275.0\Bin\glslc.exe min_reduce.comp -o min_reduce.spv
C:\VulkanSDK\1.3.275.0\Bin\glslc.exe noise_hist.comp -o noise_hist.spv
C:\VulkanSDK\1.3.275.0\Bin\glslc.exe noise_hist_render.comp -o noise_hist_render.spv
C:\VulkanSDK\1.3.275.0\Bin\glslc.exe noise_reduction.comp -o noise_reduction.spv
C:\VulkanSDK\1.3.275.0\Bin\glslc.exe gradation_curve_debug_render.comp -o gradation_curve_debug_render.spv

pause